#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

int IfLeapYear(int year) {
    if ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)) {
        return 1; 
    }
    return 0;
}

int DaysInMonth(int month, int year) {   
 
    int daysInMonth[] = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
   
    if (month == 2 && IfLeapYear(year)) {
        return 29;
    }
    return daysInMonth[month - 1]; 
}

int FirstDay(int year) {
    int day, month = 1, century, year_of_century;
    
    year_of_century = year % 100;
    century = year / 100;
  
    day = (1 + ((13 * (month + 1)) / 5) + year_of_century + (year_of_century / 4) + (century / 4) - (2 * century)) % 7;
    
    return (day + 7) % 7; 
}

void printMonth(int year, int month, int firstDay) {    
  
    char* monthNames[] = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
    
    printf("\n     %s %d\n", monthNames[month - 1], year);
    printf("Su Mo Tu We Th Fr Sa\n");
  
    for (int i = 0; i < firstDay; i++) {
        printf("   ");
    }
  
    int days = DaysInMonth(month, year);
    for (int i = 1; i <= days; i++) {
        printf("%2d ", i);
        if ((firstDay + i) % 7 == 0) {
            printf("\n");
        }
    }
    
    printf("\n");
}

void printCalendar(int year) {
    
    int firstDay = FirstDay(year);
    
    for (int month = 1; month <= 12; month++) {
        printMonth(year, month, firstDay);
        
        firstDay = (firstDay + DaysInMonth(month, year)) % 7;
    }
}

int main() {
    int year;
  
    printf("Enter a year: ");
    scanf("%d", &year);
 
    if (IfLeapYear(year)) {
        printf("%d is a leap year.\n", year);
    } else {
        printf("%d is not a leap year.\n", year);
    }
 
    printCalendar(year);
    
    return 0;
}
